apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-cilist-prod
  namespace: production
  labels:
    app: be-cilist-prod
    name: be-cilist-prod
    keel.sh/policy: major  
    keel.sh/trigger: poll  
    keel.sh/approvals: "1" 
spec:
  selector:
    matchLabels:
      app: be-cilist-prod
  replicas: 2
  template:
    metadata:
      labels:
        app: be-cilist-prod
    spec:
      containers:
      - name: be-cilist-prod
        image: rafly21/be-cilistproject:0.0.2-master
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: cm-env-be
        # - name: DATABASE_HOST
        #   value: database-1.cqaakdnejxub.ap-southeast-1.rds.amazonaws.com
        # - name: DATABASE_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-database-prod
        #       key: DATABASE_USERNAME
        # - name: DATABASE_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: secret-database-prod
        #       key: DATABASE_PASSWORD
        # - name: DATABASE_DATABASE
        #   valueFrom:
        #     configMapKeyRef:
        #       name: database-configmap-prod
        #       key: DATABASE_DATABASE
        # - name: DATABASE_PORT
        #   value: "3306"
        # - name: BASE_URL_PORT
        #   value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-be-cilist-prod
  namespace: production
spec:
  selector:
    app: be-cilist-prod
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP
    
        
