apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment-be-prod
 namespace: production
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: be-cilist-prod
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 20