apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-deployment-be-stag
 namespace: staging
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: be-cilist-stag
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 20